# Generated by Django 5.1.4 on 2024-12-22 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpost',
            name='steps',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodpost',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='step',
            name='food_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_steps', to='users.foodpost'),
        ),
    ]
