# Generated by Django 5.1.4 on 2024-12-23 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_foodpost_steps_alter_foodpost_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='reason_for_instruction',
            new_name='reason',
        ),
        migrations.RemoveField(
            model_name='foodpost',
            name='steps',
        ),
        migrations.AddField(
            model_name='foodpost',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='food_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='users.foodpost'),
        ),
    ]
