# Generated by Django 5.1.4 on 2024-12-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_reason_for_instruction_step_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpost',
            name='procedures',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
