# Generated by Django 5.1.4 on 2024-12-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_foodpost_procedures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpost',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodpost',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
